#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {d3mon5oul06}-deployment
spec:
  selector:
    matchLabels:
      app: {d3mon5oul06}-server
  replicas: 3
  template:
    metadata:
      labels:
        app: {d3mon5oul06}-server
    spec:
      containers:
      - name: {d3mon5oul06}-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/{d3m0n5oul}/tensorflow-{d3mon5oul06}:{github.sha}
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {d3mon5oul06}-service
  name: {d3mon5oul06}-service
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: {d3mon5oul06}-server
  type: LoadBalancer

  ports:
  - name: "d3mon5oul06"
    port: 8080
  selector:
    app: d3mon5oul06
