apiVersion: apps/v1
kind: Deployment
metadata:
  name: d3mon5oul06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d3mon5oul06
  template:
    metadata:
      labels:
        app: d3mon5oul06
    spec:
      containers:
      - image: okteto.dev/d3mon5oul06:latest
        name: d3mon5oul06
        envFrom:
        - configMapRef:
            name: d3mon5oul06-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: d3mon5oul06
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "d3mon5oul06"
    port: 8080
  selector:
    app: d3mon5oul06
