# Generated by Django 3.1.3 on 2023-02-24 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('numeros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero',
            name='autor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='numero',
            name='capitulos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numero',
            name='clasificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numero',
            name='genero',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='numero',
            name='lanzamiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='numero',
            name='paginas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numero',
            name='pais',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='numero',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='numero',
            name='serializacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numero',
            name='titulo',
            field=models.TextField(default=''),
        ),
    ]
